<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AmbienceSeeder extends Seeder
{
    public function run()
    {
        DB::table('ambience')->insert([
            ['ambience_id' => 1, 'ambience_name' => 'Área de Serviço'],
            ['ambience_id' => 2, 'ambience_name' => 'Banheiro'],
            ['ambience_id' => 3, 'ambience_name' => 'Quarto'],
            ['ambience_id' => 4, 'ambience_name' => 'Varanda'],
            ['ambience_id' => 5, 'ambience_name' => 'Corredor'],
            ['ambience_id' => 6, 'ambience_name' => 'Quarto Suite'],
            ['ambience_id' => 7, 'ambience_name' => 'WC Suite'],
            ['ambience_id' => 8, 'ambience_name' => 'Cozinha'],
            ['ambience_id' => 9, 'ambience_name' => 'Sala'],
            ['ambience_id' => 10, 'ambience_name' => 'Quarto Suite reversível'],
            ['ambience_id' => 11, 'ambience_name' => 'Deck'],
            ['ambience_id' => 12, 'ambience_name' => 'Dependência'],
            ['ambience_id' => 13, 'ambience_name' => 'Despensa'],
            ['ambience_id' => 14, 'ambience_name' => 'Escada'],
            ['ambience_id' => 15, 'ambience_name' => 'Escritório'],
            ['ambience_id' => 17, 'ambience_name' => 'Lavanderia'],
            ['ambience_id' => 23, 'ambience_name' => 'Área'],
            ['ambience_id' => 45, 'ambience_name' => 'Quarto 01'],
            ['ambience_id' => 46, 'ambience_name' => 'Quarto 02'],
            ['ambience_id' => 47, 'ambience_name' => 'Quarto 03'],
            ['ambience_id' => 48, 'ambience_name' => 'Quarto 04'],
            ['ambience_id' => 49, 'ambience_name' => 'Suíte 01'],
            ['ambience_id' => 50, 'ambience_name' => 'Suíte 02'],
            ['ambience_id' => 51, 'ambience_name' => 'Suíte 03'],
            ['ambience_id' => 52, 'ambience_name' => 'Suíte 04'],
            ['ambience_id' => 53, 'ambience_name' => 'Suíte 05'],
            ['ambience_id' => 54, 'ambience_name' => 'WC Suite 01'],
            ['ambience_id' => 55, 'ambience_name' => 'WC Suite 02'],
            ['ambience_id' => 56, 'ambience_name' => 'WC Suite 03'],
            ['ambience_id' => 57, 'ambience_name' => 'WC Suite 04'],
            ['ambience_id' => 58, 'ambience_name' => 'Banheiro DCE'],
            ['ambience_id' => 59, 'ambience_name' => 'Sala 360º'],
            ['ambience_id' => 60, 'ambience_name' => 'Quarto 01 em 360º'],
            ['ambience_id' => 61, 'ambience_name' => 'Quarto 02 em 360º'],
            ['ambience_id' => 62, 'ambience_name' => 'Suíte 360º'],
            ['ambience_id' => 63, 'ambience_name' => 'WC Suíte (c/ foto em 360º)'],
            ['ambience_id' => 64, 'ambience_name' => 'WC Social (c/ foto em 360º)'],
            ['ambience_id' => 65, 'ambience_name' => 'Cozinha em 360º'],
            ['ambience_id' => 66, 'ambience_name' => 'Gabinete'],
            ['ambience_id' => 67, 'ambience_name' => 'Varanda (Área escada)'],
            ['ambience_id' => 68, 'ambience_name' => 'Varanda Suíte 01'],
            ['ambience_id' => 69, 'ambience_name' => 'Wc Social'],
            ['ambience_id' => 70, 'ambience_name' => 'Hall'],
            ['ambience_id' => 71, 'ambience_name' => 'Varanda 360º'],
            ['ambience_id' => 72, 'ambience_name' => 'Suíte reversível'],
            ['ambience_id' => 73, 'ambience_name' => 'WC suíte reversível'],
            ['ambience_id' => 74, 'ambience_name' => 'Corredor 360'],
            ['ambience_id' => 75, 'ambience_name' => 'Suíte reversível 360'],
            ['ambience_id' => 76, 'ambience_name' => 'Entrada Lateral / Escada'],
            ['ambience_id' => 77, 'ambience_name' => 'Outros'],
            ['ambience_id' => 78, 'ambience_name' => 'WC Quarto 01'],
            ['ambience_id' => 79, 'ambience_name' => 'WC Quarto 02'],
            ['ambience_id' => 80, 'ambience_name' => 'Dependência de Empregada'],
            ['ambience_id' => 81, 'ambience_name' => 'WC Dep. Empregada'],
            ['ambience_id' => 82, 'ambience_name' => 'Garagem'],
            ['ambience_id' => 83, 'ambience_name' => 'Suíte'],
            ['ambience_id' => 84, 'ambience_name' => 'Jardim de Inverno Suíte'],
            ['ambience_id' => 85, 'ambience_name' => 'Jardim de Inverno'],
            ['ambience_id' => 86, 'ambience_name' => 'Entrada'],
            ['ambience_id' => 87, 'ambience_name' => 'Área de serviço/ Quintal'],
            ['ambience_id' => 88, 'ambience_name' => 'Copa'],
            ['ambience_id' => 89, 'ambience_name' => 'Wc Social 01'],
            ['ambience_id' => 90, 'ambience_name' => 'Wc Social 02'],
            ['ambience_id' => 91, 'ambience_name' => 'Recepção'],
            ['ambience_id' => 92, 'ambience_name' => 'Sala 01'],
            ['ambience_id' => 93, 'ambience_name' => 'Sala 02'],
            ['ambience_id' => 94, 'ambience_name' => 'Sala 03'],
            ['ambience_id' => 95, 'ambience_name' => 'Sala 04'],
            ['ambience_id' => 96, 'ambience_name' => 'Wc 02'],
            ['ambience_id' => 97, 'ambience_name' => 'Planta Baixa'],
            ['ambience_id' => 98, 'ambience_name' => 'Varanda Suíte'],
            ['ambience_id' => 99, 'ambience_name' => 'Corredor Inferior'],
            ['ambience_id' => 100, 'ambience_name' => 'Corredor Superior'],
            ['ambience_id' => 101, 'ambience_name' => 'Cozinha / Despensa'],
            ['ambience_id' => 102, 'ambience_name' => 'WC Serviço'],
            ['ambience_id' => 103, 'ambience_name' => 'Quarto Closet'],
            ['ambience_id' => 105, 'ambience_name' => 'Quintal'],
            ['ambience_id' => 106, 'ambience_name' => 'Quarto do Quintal'],
            ['ambience_id' => 107, 'ambience_name' => 'Fachada'],
            ['ambience_id' => 108, 'ambience_name' => 'Closet'],
            ['ambience_id' => 109, 'ambience_name' => 'Varanda (Área Superior)'],
            ['ambience_id' => 110, 'ambience_name' => 'WC Social (Superior)'],
            ['ambience_id' => 111, 'ambience_name' => 'Lavabo'],
            ['ambience_id' => 112, 'ambience_name' => 'WC Quarto 03'],
            ['ambience_id' => 113, 'ambience_name' => 'Loja'],
            ['ambience_id' => 114, 'ambience_name' => 'Varanda Suite'],
            ['ambience_id' => 115, 'ambience_name' => 'Sala e Cozinha'],
            ['ambience_id' => 116, 'ambience_name' => 'Sala 05'],
            ['ambience_id' => 117, 'ambience_name' => 'Sala (Piso Superior)'],
            ['ambience_id' => 118, 'ambience_name' => 'Suite 01 (Piso Superior)'],
            ['ambience_id' => 119, 'ambience_name' => 'Wc Suite 01 (Piso Superior)'],
            ['ambience_id' => 120, 'ambience_name' => 'Quarto (Piso Superior)'],
            ['ambience_id' => 121, 'ambience_name' => 'Varanda (Piso Superior)'],
            ['ambience_id' => 122, 'ambience_name' => 'Varanda (Piso Superior)'],
            ['ambience_id' => 123, 'ambience_name' => 'Sala/Quarto'],
            ['ambience_id' => 124, 'ambience_name' => 'Sala de Jantar'],
            ['ambience_id' => 125, 'ambience_name' => 'Corredor Externo'],
            ['ambience_id' => 126, 'ambience_name' => 'Sala 06'],
            ['ambience_id' => 127, 'ambience_name' => 'Sala 07'],
            ['ambience_id' => 128, 'ambience_name' => 'Sala 08'],
            ['ambience_id' => 129, 'ambience_name' => 'Sala 09'],
            ['ambience_id' => 130, 'ambience_name' => 'Sala 10'],
            ['ambience_id' => 131, 'ambience_name' => 'Corredor lateral esquerda'],
            ['ambience_id' => 132, 'ambience_name' => 'Corredor fundos'],
            ['ambience_id' => 133, 'ambience_name' => 'Sala 11'],
            ['ambience_id' => 134, 'ambience_name' => 'Edícula']
        ]);
    }
}